### ISSUE TITLE
Use case needed

### ISSUE THREAD

**Issue by Ubuntufanboy** [Irtiza90/colored-print#1]
I'm a little confused, What is this program supposed to help with? If we wanted colored printing we would just use colorama directly. Although It's still interesting

**Comment by Irtiza90** [comment]
It pretty prints python objects, and with `colorama`that's not the case, it cannot color print python objects

This program instead uses colorama to color the text

**Comment by Ubuntufanboy** [comment]
Ah ok. Sorry about that. Good to know!
